########################## Ubuntu 1910 ################################

build-RW:ubuntu-1910:
  extends: .linux-build-RW
  image: registry.gitlab.com/sdurobotics/docker-images/robwork-build:ubuntu-1910

build-RWS:ubuntu-1910:
  extends: .linux-build-RWS
  dependencies:
    - build-RW:ubuntu-1910
  needs: ["build-RW:ubuntu-1910"]
  image: registry.gitlab.com/sdurobotics/docker-images/robwork-build:ubuntu-1910

build-RWSim:ubuntu-1910:
  extends: .linux-build-RWSim
  dependencies:
    - build-RW:ubuntu-1910
    - build-RWS:ubuntu-1910
  needs: ["build-RW:ubuntu-1910", "build-RWS:ubuntu-1910"]
  image: registry.gitlab.com/sdurobotics/docker-images/robwork-build:ubuntu-1910

examples:ubuntu-1910:
  extends: .linux-examples
  dependencies:
    - build-RW:ubuntu-1910
    - build-RWS:ubuntu-1910
    - build-RWSim:ubuntu-1910
  needs:
    [
      "build-RW:ubuntu-1910",
      "build-RWS:ubuntu-1910",
      "build-RWSim:ubuntu-1910",
    ]
  image: registry.gitlab.com/sdurobotics/docker-images/robwork-build:ubuntu-1910

tests:ubuntu-1910:
  extends: .linux-tests
  dependencies:
    - build-RW:ubuntu-1910
    - build-RWS:ubuntu-1910
    - build-RWSim:ubuntu-1910
  needs:
    [
      "build-RW:ubuntu-1910",
      "build-RWS:ubuntu-1910",
      "build-RWSim:ubuntu-1910",
    ]
  image: registry.gitlab.com/sdurobotics/docker-images/robwork-build:ubuntu-1910
