########################## Ubuntu 2110 ################################

build-RW:ubuntu-2110:
  extends: .linux-build-RW
  image: registry.gitlab.com/sdurobotics/docker-images/robwork-build:ubuntu-2110

build-RWS:ubuntu-2110:
  extends: .linux-build-RWS
  dependencies:
    - build-RW:ubuntu-2110
  needs: ["build-RW:ubuntu-2110"]
  image: registry.gitlab.com/sdurobotics/docker-images/robwork-build:ubuntu-2110

build-RWSim:ubuntu-2110:
  extends: .linux-build-RWSim
  dependencies:
    - build-RW:ubuntu-2110
    - build-RWS:ubuntu-2110
  needs: ["build-RW:ubuntu-2110", "build-RWS:ubuntu-2110"]
  image: registry.gitlab.com/sdurobotics/docker-images/robwork-build:ubuntu-2110

examples:ubuntu-2110:
  extends: .linux-examples
  dependencies:
    - build-RW:ubuntu-2110
    - build-RWS:ubuntu-2110
    - build-RWSim:ubuntu-2110
  needs:
    [
      "build-RW:ubuntu-2110",
      "build-RWS:ubuntu-2110",
      "build-RWSim:ubuntu-2110",
    ]
  image: registry.gitlab.com/sdurobotics/docker-images/robwork-build:ubuntu-2110

tests:ubuntu-2110:
  extends: .linux-tests
  dependencies:
    - build-RW:ubuntu-2110
    - build-RWS:ubuntu-2110
    - build-RWSim:ubuntu-2110
  needs:
    [
      "build-RW:ubuntu-2110",
      "build-RWS:ubuntu-2110",
      "build-RWSim:ubuntu-2110",
    ]
  image: registry.gitlab.com/sdurobotics/docker-images/robwork-build:ubuntu-2110
