########################## WINDOWS vs16 ################################

build-RW:windows10-vs16:
  extends: .windows-build-RW

build-RWS:windows10-vs16:
  extends: .windows-build-RWS
  dependencies:
    - build-RW:windows10-vs16
  needs: ["build-RW:windows10-vs16"]

build-RWSim:windows10-vs16:
  extends: .windows-build-RWSim
  dependencies:
    - build-RW:windows10-vs16
    - build-RWS:windows10-vs16
  needs: ["build-RW:windows10-vs16", "build-RWS:windows10-vs16"]

installer:windows10-vs16:
  extends: .windows-build-installers
  dependencies:
    - build-RW:windows10-vs16
    - build-RWS:windows10-vs16
  needs:
    [
      "build-RW:windows10-vs16",
      "build-RWS:windows10-vs16",
    ]

examples:windows10-vs16:
  extends: .windows-examples
  dependencies:
    - build-RW:windows10-vs16
    - build-RWS:windows10-vs16
    - build-RWSim:windows10-vs16
  needs:
    [
      "build-RW:windows10-vs16",
      "build-RWS:windows10-vs16",
      "build-RWSim:windows10-vs16",
    ]

tests:windows10-vs16:
  extends: .windows-tests
  dependencies:
    - build-RW:windows10-vs16
    - build-RWS:windows10-vs16
    - build-RWSim:windows10-vs16
  needs:
    [
      "build-RW:windows10-vs16",
      "build-RWS:windows10-vs16",
      "build-RWSim:windows10-vs16",
    ]