#!/bin/bash

#The preinst script may be called in the following ways:

#   new-preinst install
#   new-preinst install old-version
#   new-preinst upgrade old-version
#The package will not yet be unpacked, so the preinst script cannot rely on any files included in its package. 

#   old-preinst abort-upgrade new-version
#Called during error handling of an upgrade that failed after unpacking the new package because the postrm upgrade action failed.

ubuntu_codename=$(cat /etc/os-release | grep -oP '(?<=UBUNTU_CODENAME=).*')
file="/etc/apt/sources.list.d/sdurobotics-ubuntu-ur-rtde-$ubuntu_codename.list"
if [[ ! -e "$file" ]] ; then
    echo "deb http://ppa.launchpad.net/sdurobotics/ur-rtde/ubuntu $ubuntu_codename main" > test.txt
    echo "# deb-src http://ppa.launchpad.net/sdurobotics/ur-rtde/ubuntu $ubuntu_codename main" >> test.txt
fi

