######################## BUILD Doc ##########################################

build:doc-2204:
  extends: .linux-doc
  dependencies:
    - build-RW:ubuntu-2204
    - build-RWS:ubuntu-2204
    - build-RWSim:ubuntu-2204
  needs:
    [
      "build-RW:ubuntu-2204",
      "build-RWS:ubuntu-2204",
      "build-RWSim:ubuntu-2204",
    ]
  image: registry.gitlab.sdu.dk/sdurobotics/docker-images/robwork-build:ubuntu-2204-doc

######################## deploy Doc ##########################################

pages:
  stage: deploy
  tags:
    - linux
  only:
    refs:
      - master@sdurobotics/RobWork
      - schedules
      - web
  variables:
    GIT_STRATEGY: none
  script:
    - cd public
    #- "sshpass -e sftp robwork@www5.sdu.dk:htdocs <<< $'put -r ./*'"
    - echo "Deploying documentation."
  dependencies:
    - build:doc-2204
  needs: ["build:doc-2204"]
  image: registry.gitlab.sdu.dk/sdurobotics/docker-images/robwork-build:ubuntu-2204-doc
  artifacts:
    paths:
      - public
    expire_in: 1 week
